---
  - name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
    raw: apt-get install python-minimal aptitude -y
  - name: Update apt cache
    apt: update_cache=yes
  - name: Upgrade
    apt:
      upgrade: yes

  - name: Installing apache
    apt: name=apache2 state=present
  - name: New virtual site
    template:
       src=siteansible.conf.j2
       dest=/etc/apache2/sites-available/sitioiaw.conf       
  - name: delete virtual host by default
    file:
      path=/etc/apache2/sites-enabled/000-default.conf
      state=absent
  - name: delete index by default
    file:
      path=/var/www/html/index.html
      state=absent
  - name: New index
    template:
       src=index.html
       dest=/var/www/html/index.html
  - name: Adding info.php
    template:
       src=info.php
       dest=/var/www/html/info.php
  - name: Activate the new site
    file:
       src=/etc/apache2/sites-available/sitioiaw.conf
       dest=/etc/apache2/sites-enabled/sitioiaw.conf
       state=link
  - name: Activate apache
    apache2_module: state=present name=userdir
    notify:
      - restart apache
  - name: Installing mysql
    apt: name=mysql-server state=present
  - name: Installing modulo python-mysqldb
    apt: name=python-mysqldb state=present
  - name: Adding databases
    mysql_db: name=ASIR
                  state=present
    notify:
      - restart mysql
  - name: Installing PHP
    apt: name=php state=present
  - name: Installing php
    apt: name={{ item }}
         state=latest
    with_items:
          - php-mysql
          - libapache2-mod-php